#ifndef LENS_BUS_H
#define LENS_BUS_H

#include "gpio_rpi.h"

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LENS_SPEED_SLOW = 0,
    LENS_SPEED_FAST = 1,
} lens_speed_t;

typedef struct {
    unsigned mosi_gpio;          /* Camera/Pi -> lens, Canon DCL in your notes. */
    unsigned miso_gpio;          /* Lens -> camera/Pi, Canon DLC in your notes. */
    unsigned clk_gpio;           /* Open-drain/open-collector clock line. */

    uint32_t slow_period_ns;     /* Full clock period, default ~12.5 us. */
    uint32_t fast_period_ns;     /* Full clock period, default 2.0 us. */
    uint32_t sample_delay_ns;    /* Extra delay after CLK rising before MISO sample. */

    /* MOSI timing, normal mode:
     *   - CLK idles/released high.
     *   - MOSI is prepared BEFORE the next falling edge.
     *   - For bits after the first, MOSI is updated during the high phase,
     *     away from the rising/falling edges. With mosi_setup_ns == 0, the
     *     update is placed halfway through the high phase, so the new value is
     *     valid for roughly half a high-period before the next falling edge.
     *
     * This fixes the previous behaviour where MOSI changed immediately after
     * the falling edge, which made the first falling edge look ignored on the
     * oscilloscope/logic analyser.
     */
    uint32_t mosi_setup_ns;      /* 0 = automatic: half of CLK-high time. */
    bool legacy_mosi_after_fall; /* Old diagnostic mode only. Default false. */

    bool clk_internal_pullup;    /* Configure weak Pi pull-up on CLK input. */
    bool wait_clk_high;          /* Respect lens clock stretching before/after edges. */
    uint32_t clk_high_timeout_us;
} lens_bus_config_t;

typedef struct {
    rpi_gpio_t gpio;
    lens_bus_config_t cfg;

    uint32_t mosi_mask;
    uint32_t miso_mask;
    uint32_t clk_mask;
    unsigned mosi_bank;
    unsigned miso_bank;
    unsigned clk_bank;

    unsigned clk_fsel_index;
    uint32_t clk_fsel_clear_mask;
    uint32_t clk_fsel_output_bits;

    bool has_arch_timer;
    uint64_t arch_timer_freq_hz;
} lens_bus_t;

void lens_bus_default_config(lens_bus_config_t *cfg);
int  lens_bus_open(lens_bus_t *bus, const lens_bus_config_t *cfg);
void lens_bus_close(lens_bus_t *bus);

/* Low-level CLK controls. CLK high is generated by release/high-Z, never by
 * push-pull driving high. */
void lens_clk_drive_low(lens_bus_t *bus);
void lens_clk_release(lens_bus_t *bus);
int  lens_clk_read(const lens_bus_t *bus);
int  lens_wait_clk_high(lens_bus_t *bus, uint32_t timeout_us);

int lens_bus_transfer_period(lens_bus_t *bus,
                             uint32_t period_ns,
                             const uint8_t *tx,
                             uint8_t *rx,
                             size_t len);

int lens_bus_transfer(lens_bus_t *bus,
                      lens_speed_t speed,
                      const uint8_t *tx,
                      uint8_t *rx,
                      size_t len);

const char *lens_strerror(int rc);

#ifdef __cplusplus
}
#endif

#endif /* LENS_BUS_H */
